auto_buy: false
skins:
  # Talon Knife Case Hardened Tier 1 Blue Gem patterns
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Factory%20New%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: &talon_tier1
      - 10
      - 55
      - 180
      - 222
      - 241
      - 316
      - 528
      - 602
      - 837
      - 899
      - 923
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Factory%20New%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier1
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Minimal%20Wear%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier1
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Minimal%20Wear%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier1
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Field-Tested%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier1
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Field-Tested%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier1
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Well-Worn%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier1
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Well-Worn%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier1
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Battle-Scarred%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier1
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Battle-Scarred%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier1

  # Talon Knife Case Hardened Tier 2 Blue Gem patterns
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Factory%20New%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: &talon_tier2
      - 3
      - 14
      - 56
      - 80
      - 114
      - 116
      - 170
      - 176
      - 185
      - 199
      - 299
      - 311
      - 345
      - 351
      - 357
      - 365
      - 379
      - 468
      - 501
      - 506
      - 570
      - 576
      - 583
      - 609
      - 657
      - 707
      - 805
      - 807
      - 819
      - 866
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Factory%20New%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier2
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Minimal%20Wear%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier2
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Minimal%20Wear%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier2
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Field-Tested%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier2
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Field-Tested%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier2
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Well-Worn%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier2
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Well-Worn%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier2
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Battle-Scarred%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier2
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Battle-Scarred%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier2

  # Talon Knife Case Hardened Tier 3 Blue Gem patterns
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Factory%20New%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: &talon_tier3
      - 18
      - 19
      - 46
      - 58
      - 95
      - 111
      - 130
      - 137
      - 186
      - 203
      - 291
      - 328
      - 367
      - 374
      - 456
      - 473
      - 488
      - 491
      - 505
      - 516
      - 533
      - 599
      - 621
      - 658
      - 660
      - 669
      - 693
      - 749
      - 761
      - 798
      - 815
      - 830
      - 873
      - 883
      - 891
      - 941
      - 960
      - 976
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Factory%20New%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier3
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Minimal%20Wear%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier3
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Minimal%20Wear%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier3
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Field-Tested%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier3
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Field-Tested%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier3
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Well-Worn%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier3
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Well-Worn%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier3
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Battle-Scarred%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier3
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Battle-Scarred%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier3

  # Talon Knife Case Hardened Tier 4 Blue Gem patterns
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Factory%20New%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: &talon_tier4
      - 59
      - 67
      - 70
      - 72
      - 75
      - 76
      - 77
      - 88
      - 100
      - 115
      - 138
      - 157
      - 168
      - 188
      - 191
      - 218
      - 248
      - 255
      - 280
      - 292
      - 293
      - 313
      - 342
      - 347
      - 372
      - 381
      - 383
      - 391
      - 403
      - 404
      - 411
      - 431
      - 446
      - 447
      - 458
      - 481
      - 496
      - 497
      - 503
      - 504
      - 507
      - 547
      - 557
      - 577
      - 598
      - 606
      - 607
      - 618
      - 633
      - 640
      - 668
      - 681
      - 702
      - 704
      - 729
      - 730
      - 780
      - 820
      - 821
      - 835
      - 838
      - 881
      - 890
      - 917
      - 927
      - 933
      - 956
      - 959
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Factory%20New%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier4
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Minimal%20Wear%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier4
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Minimal%20Wear%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier4
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Field-Tested%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier4
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Field-Tested%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier4
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Well-Worn%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier4
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Well-Worn%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier4
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Battle-Scarred%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier4
  - url: https://steamcommunity.com/market/listings/730/%E2%98%85%20StatTrak%E2%84%A2%20Talon%20Knife%20%7C%20Case%20Hardened%20%28Battle-Scarred%29
    float: null
    price: null
    number_of_stickers: null
    pages: null
    pattern: *talon_tier4
